//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class tHourType
    {
        public tHourType()
        {
            this.tInCharges = new HashSet<tInCharge>();
        }
    
        public int HourTypeId { get; set; }
        public string HourTypeDescription { get; set; }
    
        public virtual ICollection<tInCharge> tInCharges { get; set; }
    }
}
