//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class tInCharge
    {
        public long ICId { get; set; }
        public long StaffId { get; set; }
        public int HourType { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual tHourType tHourType { get; set; }
        public virtual tStaff tStaff { get; set; }
    }
}
