//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class tMember
    {
        public long MemberId { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Cellphone { get; set; }
        public Nullable<long> CardId { get; set; }
        public Nullable<int> MemberType { get; set; }
    
        public virtual tMemberType tMemberType { get; set; }
        public virtual tCard tCard { get; set; }
    }
}
