//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class tOrderItem
    {
        public int OrderItemId { get; set; }
        public int OrderId { get; set; }
        public int PriceId { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<long> TotalAmount { get; set; }
    
        public virtual tOrder tOrder { get; set; }
        public virtual tPrice tPrice { get; set; }
    }
}
