//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class tStaff
    {
        public tStaff()
        {
            this.tInCharges = new HashSet<tInCharge>();
        }
    
        public long StaffId { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Cellphone { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual ICollection<tInCharge> tInCharges { get; set; }
    }
}
