//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class tStaff
    {
        public tStaff()
        {
            this.tStaffAreas = new HashSet<tStaffArea>();
            this.tStaffClasses = new HashSet<tStaffClass>();
        }
    
        public long Id { get; set; }
        public string RUT { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Phone { get; set; }
        public string Adress { get; set; }
        public string City { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual ICollection<tStaffArea> tStaffAreas { get; set; }
        public virtual ICollection<tStaffClass> tStaffClasses { get; set; }
    }
}
