//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MakeMake
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCard
    {
        public long CardId { get; set; }
        public bool Monthly { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> Tickets { get; set; }
        public System.DateTime Changed { get; set; }
    }
}
