//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MakeMake
{
    using System;
    using System.Collections.Generic;
    
    public partial class tStaffArea
    {
        public long ID { get; set; }
        public long StaffId { get; set; }
        public int AreaId { get; set; }
    
        public virtual tArea tArea { get; set; }
        public virtual tStaff tStaff { get; set; }
    }
}
