//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HerokoRima
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MakeMakeEntities : DbContext
    {
        public MakeMakeEntities()
            : base("name=MakeMakeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tCardUsage> tCardUsages { get; set; }
        public virtual DbSet<tClass> tClasses { get; set; }
        public virtual DbSet<tDropIn> tDropIns { get; set; }
        public virtual DbSet<tMember> tMembers { get; set; }
        public virtual DbSet<tMonth> tMonths { get; set; }
        public virtual DbSet<tStaff> tStaffs { get; set; }
        public virtual DbSet<tTicket> tTickets { get; set; }
        public virtual DbSet<tCard> tCards { get; set; }
    }
}
