//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HerokoRima
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCardUsage
    {
        public long CUId { get; set; }
        public long CardId { get; set; }
        public Nullable<System.DateTime> EntranceDate { get; set; }
    }
}
