//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HerokoRima
{
    using System;
    using System.Collections.Generic;
    
    public partial class tStaff
    {
        public long Id { get; set; }
        public string RUT { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Area { get; set; }
    }
}
