//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HerokoRima
{
    using System;
    using System.Collections.Generic;
    
    public partial class tTicket
    {
        public long Id { get; set; }
        public long CardNo { get; set; }
        public Nullable<long> Quantity { get; set; }
        public Nullable<System.DateTime> Purchased { get; set; }
        public Nullable<long> Amount { get; set; }
    }
}
